apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps-kustomization.yaml
- cert-certificates-kustomization.yaml
- cert-issuers-kustomization.yaml
- config-kustomization.yaml
- eso-stores-kustomization.yaml
- eso-externalsecrets-kustomization.yaml
- eso-infra-externalsecrets-kustomization.yaml
- gotk-components.yaml
- gotk-sync.yaml
- infra-kustomization.yaml
- istio-base-kustomization.yaml
- istio-sandbox-kustomization.yaml
- otel-collectors-base-kustomization.yaml
