apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-helmrelease
  namespace: external-dns
  annotations:
    config-updated: "${CONFIG_TIMESTAMP}"
spec:
  interval: 60m # Shorter interval for local development
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-base-values
      valuesKey: base.values.yaml
    - kind: ConfigMap
      name: external-dns-level-values
      valuesKey: lcl.values.yaml
  values:
    replicaCount: 0 # Single replica for local
