apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-helmrelease
  namespace: external-secrets
  annotations:
    config-updated: "${CONFIG_TIMESTAMP}"
spec:
  interval: 60m # Shorter interval for local development
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-base-values
      valuesKey: base.values.yaml
    - kind: ConfigMap
      name: external-secrets-level-values
      valuesKey: lcl.values.yaml
