---
#apiVersion: source.toolkit.fluxcd.io/v1
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloak-helmrepo
  namespace: keycloak
spec:
  interval: 240m
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    # SemVer range reference: https://github.com/Masterminds/semver#checking-version-constraints
    semver: "25.x.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-helmrelease
  namespace: keycloak
spec:
  suspend: false
  interval: 240m
  releaseName: keycloak-release
  install:
    crds: Create
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: keycloak-helmrepo
    namespace: keycloak
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-values
      valuesKey: values.yaml
      optional: false
