---
#apiVersion: source.toolkit.fluxcd.io/v1
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: oauth2-proxy-helmrepo
  namespace: oauth2-proxy
spec:
  interval: 240m
  url: oci://registry-1.docker.io/bitnamicharts/oauth2-proxy
  ref:
    # SemVer range reference: https://github.com/Masterminds/semver#checking-version-constraints
    semver: "6.x.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-helmrelease
  namespace: oauth2-proxy
spec:
  suspend: false
  interval: 240m
  releaseName: oauth2-proxy-rel
  install:
    crds: Create
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: oauth2-proxy-helmrepo
    namespace: oauth2-proxy
  valuesFrom:
    - kind: ConfigMap
      name: oauth2-proxy-values
      valuesKey: values.yaml
      optional: false
